---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/ci"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "docker"
    directory: "/ubuntu-full"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Berlin"
