---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: sunday
      timezone: "Europe/Berlin"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: sunday
      timezone: "Europe/Berlin"
