name: ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      blog:
        description: "Build Manually"
        required: true
        default: 'yes'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push [linux amd64]
        uses: docker/build-push-action@v5
        with:
          push: true
          context: /ci
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci:amd64

      - name: Build and push [linux arm64]
        uses: docker/build-push-action@v5
        with:
          push: true
          context: /ci
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci:arm64
          build-args:
            TERRAFORM_ARCH=arm64
            TMATE_ARCH=arm64v8
            TERRAFORM_OS=linux

      - name: Build and push [darwin arm64]
        uses: docker/build-push-action@v5
        with:
          push: true
          context: /ci
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci:darwin_arm64
          build-args: |
            TERRAFORM_ARCH=arm64
            TMATE_ARCH=arm64v8
            TERRAFORM_OS=darwin
