name: ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      blog:
        description: "Build Manually"
        required: true
        default: 'yes'

jobs:
  setup-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Matrix
        id: setup-matrix
        run: |
          MATRIX=$(git diff --find-renames=100% --name-only $(git merge-base remotes/origin/master $(git rev-parse --abbrev-ref HEAD)) | grep '^[a-zA-Z0-9\-]*\/' | sed 's#/.*##g' | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT
          jq <<< "${MATRIX}"

  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push [amd64]
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./ci
          file: ./ci/Dockerfile
          platforms: linux/amd64
          tags:
            - ${{ secrets.DOCKERHUB_USERNAME }}/ci:latest
            - ${{ secrets.DOCKERHUB_USERNAME }}/ci:amd64

      - name: Build and push [arm64]
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./ci
          file: ./ci/Dockerfile
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci:arm64
          build-args: |
            ARCH=arm64
            TMATE_ARCH=arm64v8
            
